In [2]:
import sys
from pathlib import Path

ROOT = Path.cwd().parent
sys.path.insert(0, str(ROOT))

from src.inf8239_u01.data import download_csv

URL = "https://archive.ics.uci.edu/static/public/697/data.csv"

path = download_csv(URL)

print(path)

data\raw\dataset.csv

In [3]:
import pandas as pd

df = pd.read_csv("data/raw/dataset.csv")

print("Dimensiones:", df.shape)
print("\nTipos de datos:")
print(df.dtypes)

print("\nPrimeras filas:")
display(df.head())

print("\nÚltimas filas:")
display(df.tail())

assert not df.empty

Dimensiones: (4424, 37)

Tipos de datos:
Marital Status                                      int64
Application mode                                    int64
Application order                                   int64
Course                                              int64
Daytime/evening attendance                          int64
Previous qualification                              int64
Previous qualification (grade)                    float64
Nacionality                                         int64
Mother's qualification                              int64
Father's qualification                              int64
Mother's occupation                                 int64
Father's occupation                                 int64
Admission grade                                   float64
Displaced                                           int64
Educational special needs                           int64
Debtor                                              int64
Tuition fees up to date                             int64
Gender                                              int64
Scholarship holder                                  int64
Age at enrollment                                   int64
International                                       int64
Curricular units 1st sem (credited)                 int64
Curricular units 1st sem (enrolled)                 int64
Curricular units 1st sem (evaluations)              int64
Curricular units 1st sem (approved)                 int64
Curricular units 1st sem (grade)                  float64
Curricular units 1st sem (without evaluations)      int64
Curricular units 2nd sem (credited)                 int64
Curricular units 2nd sem (enrolled)                 int64
Curricular units 2nd sem (evaluations)              int64
Curricular units 2nd sem (approved)                 int64
Curricular units 2nd sem (grade)                  float64
Curricular units 2nd sem (without evaluations)      int64
Unemployment rate                                 float64
Inflation rate                                    float64
GDP                                               float64
Target                                                str
dtype: object

Primeras filas:

,Marital Status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

Últimas filas:

,Marital Status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
4419,1,1,6,9773,1,1,125.0,1,1,1,...,0,6,8,5,12.666667,0,15.5,2.8,-4.06,Graduate
4420,1,1,2,9773,1,1,120.0,105,1,1,...,0,6,6,2,11.000000,0,11.1,0.6,2.02,Dropout
4421,1,1,1,9500,1,1,154.0,1,37,37,...,0,8,9,1,13.500000,0,13.9,-0.3,0.79,Dropout
4422,1,1,1,9147,1,1,180.0,1,37,37,...,0,5,6,5,12.000000,0,9.4,-0.8,-3.12,Graduate
4423,1,10,1,9773,1,1,152.0,22,38,37,...,0,6,6,6,13.000000,0,12.7,3.7,-1.70,Graduate

In [4]:
audit = pd.DataFrame({
    "tipo": df.dtypes.astype(str),
    "ausentes": df.isna().sum(),
    "porcentaje_ausente": (df.isna().mean() * 100).round(2),
    "unicos": df.nunique(dropna=False)
}).sort_values(
    "porcentaje_ausente",
    ascending=False
)

print("Duplicados:", df.duplicated().sum())

display(audit)

Duplicados: 0

,tipo,ausentes,porcentaje_ausente,unicos
Marital Status,int64,0,0.0,6
Application mode,int64,0,0.0,18
Application order,int64,0,0.0,8
Course,int64,0,0.0,17
Daytime/evening attendance,int64,0,0.0,2
Previous qualification,int64,0,0.0,17
Previous qualification (grade),float64,0,0.0,101
Nacionality,int64,0,0.0,21
Mother's qualification,int64,0,0.0,29
Father's qualification,int64,0,0.0,34
Mother's occupation,int64,0,0.0,32
Father's occupation,int64,0,0.0,46
Admission grade,float64,0,0.0,620
Displaced,int64,0,0.0,2
Educational special needs,int64,0,0.0,2
Debtor,int64,0,0.0,2
Tuition fees up to date,int64,0,0.0,2
Gender,int64,0,0.0,2
Scholarship holder,int64,0,0.0,2
Age at enrollment,int64,0,0.0,46
International,int64,0,0.0,2
Curricular units 1st sem (credited),int64,0,0.0,21
Curricular units 1st sem (enrolled),int64,0,0.0,23
Curricular units 1st sem (evaluations),int64,0,0.0,35
Curricular units 1st sem (approved),int64,0,0.0,23
Curricular units 1st sem (grade),float64,0,0.0,797
Curricular units 1st sem (without evaluations),int64,0,0.0,11
Curricular units 2nd sem (credited),int64,0,0.0,19
Curricular units 2nd sem (enrolled),int64,0,0.0,22
Curricular units 2nd sem (evaluations),int64,0,0.0,30
Curricular units 2nd sem (approved),int64,0,0.0,20
Curricular units 2nd sem (grade),float64,0,0.0,782
Curricular units 2nd sem (without evaluations),int64,0,0.0,10
Unemployment rate,float64,0,0.0,10
Inflation rate,float64,0,0.0,9
GDP,float64,0,0.0,10
Target,str,0,0.0,3

In [5]:
TARGET = "Target"

DROP_COLUMNS = []

assert TARGET in df.columns

X = df.drop(columns=[TARGET] + DROP_COLUMNS)
y = df[TARGET]

print("Target:", TARGET)
print("\nDistribución del target:")
print(y.value_counts(dropna=False))

print("\nNúmero de clases:", y.nunique())

assert y.notna().all()
assert y.nunique() >= 2

Target: Target

Distribución del target:
Target
Graduate    2209
Dropout     1421
Enrolled     794
Name: count, dtype: int64

Número de clases: 3

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

num_cols = X.select_dtypes(include="number").columns.tolist()
cat_cols = X.select_dtypes(exclude="number").columns.tolist()

num_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scale", StandardScaler())
])

cat_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocess = ColumnTransformer([
    ("num", num_pipe, num_cols),
    ("cat", cat_pipe, cat_cols)
])

print("Variables numéricas:", len(num_cols))
print("Variables categóricas:", len(cat_cols))
print("\nCategóricas:")
print(cat_cols)

Variables numéricas: 36
Variables categóricas: 0

Categóricas:
[]

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, f1_score

Xtr, Xte, ytr, yte = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

dummy = Pipeline([
    ("prep", preprocess),
    ("model", DummyClassifier(strategy="most_frequent"))
])

svm = Pipeline([
    ("prep", preprocess),
    ("model", SVC(
        C=1,
        gamma="scale",
        probability=True,
        random_state=42
    ))
])

for name, model in {
    "dummy": dummy,
    "svm": svm
}.items():

    model.fit(Xtr, ytr)
    pred = model.predict(Xte)

    print(f"\n{name.upper()}")
    print("F1 macro:", f1_score(yte, pred, average="macro"))

print("\nREPORTE DE CLASIFICACIÓN - SVM")
print(classification_report(yte, svm.predict(Xte)))

DUMMY
F1 macro: 0.22205476011052497

c:\Users\raine\Desktop\Ciencias de Datos II\INF8239_U01\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

SVM
F1 macro: 0.6784703597430611

REPORTE DE CLASIFICACIÓN - SVM
              precision    recall  f1-score   support

     Dropout       0.84      0.73      0.78       284
    Enrolled       0.50      0.35      0.41       159
    Graduate       0.77      0.93      0.84       442

    accuracy                           0.76       885
   macro avg       0.71      0.67      0.68       885
weighted avg       0.75      0.76      0.75       885